object Dependencies {
    const val composeUi = "androidx.compose.ui:ui:${Versions.composeVersion}"
    const val composeMaterial = "androidx.compose.material:material:${Versions.composeVersion}"
    const val composeUiToolingPreview = "androidx.compose.ui:ui-tooling-preview:${Versions.composeVersion}"
    const val composeActivity = "androidx.activity:activity-compose:${Versions.composeActivityVersion}"
    const val composeUiUiTestJunit4 = "androidx.compose.ui:ui-test-junit4:${Versions.composeVersion}"
    const val composeUiUiTooling = "androidx.compose.ui:ui-tooling:${Versions.composeVersion}"
    const val retrofit2Retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofitVersion}"
    const val retrofit2ConverterJson = "com.squareup.retrofit2:converter-gson:${Versions.retrofitVersion}"
    const val retrofit2AdapterRxjava2 = "com.squareup.retrofit2:adapter-rxjava2:${Versions.retrofitVersion}"
    const val okhttpLoggingInterceptor = "com.squareup.okhttp3:logging-interceptor:${Versions.okhttpLoggingInterceptor}"
    const val kotlinCoroutinesAndroid = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.kotlinCoroutinesVersion}"
    const val kotlinCoroutinesCore = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.kotlinCoroutinesVersion}"
    const val daggerHilt = "com.google.dagger:hilt-android:${Versions.daggerHiltVersion}"
    const val daggerHiltCompiler =
        "com.google.dagger:hilt-compiler:${Versions.daggerHiltVersion}"
    const val rxJava2RxAndroid = "io.reactivex.rxjava2:rxandroid:${Versions.rxJava2RxAndroidVersion}"
    const val rxJava3RxJava = "io.reactivex.rxjava3:rxjava:${Versions.rxJava3RxJavaVersion}"
    const val lifecycleRuntimeKtx = "androidx.lifecycle:lifecycle-runtime-ktx:${Versions.lifecycleRuntimeKtxVersion}"
    const val lifecycleCommonJava8 = "androidx.lifecycle:lifecycle-common-java8:${Versions.lifecycleCommonJava8Version}"
    const val lifecycleExtensions = "androidx.lifecycle:lifecycle-extensions:${Versions.lifecycleExtensionsVersion}"
    const val androidxCoreCoreKtx = "androidx.core:core-ktx:${Versions.androidxCoreCoreKtxVersion}"
    const val androidxAppcompatAppcompat = "androidx.appcompat:appcompat:${Versions.androidxAppcompatAppcompatVersion}"
    const val comGoogleAndroidMaterialMaterial = "com.google.android.material:material:${Versions.comGoogleAndroidMaterialMaterialVersion}"
    const val composeConstraintLayout = "androidx.constraintlayout:constraintlayout-compose:${Versions.composeConstraintLayoutVersion}"
    const val dataBinding = "androidx.databinding:databinding-runtime:${Versions.dataBindingVersion}"
    const val junit = "junit:junit:${Versions.junitVersion}"
    const val androidxTestExtJunit = "androidx.test.ext:junit:${Versions.junitVersion}"
    const val androidxEspressoCore = "androidx.test.espresso:espresso-core:${Versions.androidxEspressoCoreVersion}"
}