object Versions {
    const val composeVersion = "1.0.3"
    const val composeActivityVersion = "1.4.0-beta01"
    const val composeConstraintLayoutVersion = "1.0.0-rc01"
    const val kotlinVersion = "1.5.21"
    const val retrofitVersion = "2.7.0"
    const val kotlinCoroutinesVersion = "1.3.9"
    const val lifecycleRuntimeKtxVersion = "2.4.0-rc01"
    const val okhttpLoggingInterceptor = "4.2.1"
    const val daggerHiltVersion = "2.34.1-beta"
    const val rxJava2RxAndroidVersion = "2.1.1"
    const val rxJava3RxJavaVersion = "3.0.0-RC6"
    const val lifecycleCommonJava8Version = "2.3.1"
    const val lifecycleExtensionsVersion = "2.2.0"
    const val androidxCoreCoreKtxVersion = "1.6.0"
    const val androidxAppcompatAppcompatVersion = "1.3.1"
    const val comGoogleAndroidMaterialMaterialVersion = "1.4.0"
    const val dataBindingVersion = "4.1.3"
    const val toolsBuildGradleVersion = "7.0.3"
    const val kotlinGradlePluginVersion = "1.5.21"
    const val daggerHiltAndroidGradlePluginVersion = "2.39.1"
    const val jvmTargetVersion = "1.8"
    const val jvmTarget = "11"
    const val junitVersion = "4.13.2"
    const val androidxTestExtJunitVersion = "1.1.3"
    const val androidxEspressoCoreVersion = "3.4.0"
}